name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref || github.ref }}
          persist-credentials: true

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v5
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Fix auto-fixable problems
        run: pnpm lint

      - name: Add, commit and push changed files
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'chore(ci): apply lint auto-fixes'
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
